# Generated by Django 5.1.2 on 2024-10-19 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_remove_student_teacher_alter_student_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='teachers',
            field=models.ManyToManyField(related_name='students', to='school.teacher'),
        ),
        migrations.DeleteModel(
            name='TeacherStudent',
        ),
    ]
